apiVersion: apps/v1
kind: Deployment
metadata:
  name: administracao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: administracao
  template:
    metadata:
      labels:
        app: administracao
    spec:
      containers:
        - name: administracao-container
          image: keyssong/administracao:latest  # 🔹 Buscar no Docker Hub
          imagePullPolicy: Always           # 🔹 Sempre buscar a versão mais recente
          ports:
            - containerPort: 8086
